# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeasy" do
  name "kubeasy"
  desc "CLI tool to learn Kubernetes through practical challenges"
  homepage "https://kubeasy.dev"
  version "2.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeasy"

  on_macos do
    on_intel do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_darwin_amd64.tar.gz"
      sha256 "6998ee02ab0d83725715fe124eda9c757c3f48469f762be14def6900399b7119"
    end
    on_arm do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_darwin_arm64.tar.gz"
      sha256 "f60637f644c7e029ba9a5486ab26cce399cc2648a6cd5f2287c143f7233ed241"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_linux_amd64.tar.gz"
      sha256 "040997b3be0b028d6e5037ea552d1fd8da0ac90bb84bfc97826b98b485639ebf"
    end
    on_arm do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_linux_arm64.tar.gz"
      sha256 "f96e3aeabe33626bfe34606ee45d5edbb96ab6f39a6ae447325dbd231cf9c2c5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeasy"]
    end
  end

  # No zap stanza required
end
