# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeasy" do
  name "kubeasy"
  desc "CLI tool to learn Kubernetes through practical challenges"
  homepage "https://kubeasy.dev"
  version "2.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeasy"

  on_macos do
    on_intel do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_darwin_amd64.tar.gz"
      sha256 "76219078872d3cde59f18189f796ae26a8cc92afd6bfd1bf641525517c5439ab"
    end
    on_arm do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_darwin_arm64.tar.gz"
      sha256 "bb8c1ed657ce61fd0337de8c2137b1f20f0b5b26bec983c832070ce93cecd0b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_linux_amd64.tar.gz"
      sha256 "30861ce1ed1060c12215d01a56de38d0ffc2bacb2891f54df71333eae44b67aa"
    end
    on_arm do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_linux_arm64.tar.gz"
      sha256 "6aecbbc9d9bddcf048262961e6aef503657f8e3d0e241adb5050de6756f3db96"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeasy"]
    end
  end

  # No zap stanza required
end
