# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeasy" do
  name "kubeasy"
  desc "CLI tool to learn Kubernetes through practical challenges"
  homepage "https://kubeasy.dev"
  version "2.5.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeasy"

  on_macos do
    on_intel do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_darwin_amd64.tar.gz"
      sha256 "3e1740ff27d6d9b5d4aa73257afd7b2ef541b90c07a0c4f902ee09b79fa2597d"
    end
    on_arm do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_darwin_arm64.tar.gz"
      sha256 "aeeae20b4619d566493a110ad52bc5349cdf2242afb94a12c242533387c923a4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_linux_amd64.tar.gz"
      sha256 "c1ac709c76d44cd32438f7d00e8b356c34564b80895afa660bc58243976d13a4"
    end
    on_arm do
      url "https://github.com/kubeasy-dev/kubeasy-cli/releases/download/v#{version}/kubeasy-cli_v#{version}_linux_arm64.tar.gz"
      sha256 "4ebba397e279bb2e3e5530fcea2c34bd3e296b6dd96e36fd1be2aa50cbeeb78c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeasy"]
    end
  end

  # No zap stanza required
end
